module.exports = {
	VERIFY_TOKEN: 'sivansivansivan',
	PAGE_TOKEN: 'EAAOPue2B4z4BAMzZA9isR1IXsh6dbZBtSKm4wJIJqBNPgl5a5VsZA6EfrmZAQcxTVJuqwUlH0JtsxvzsG9sEwvzcHH3eHTV1Eom1ZAcZBuyi6S8ZAeiigPrErAdVffxNtYLS5db8DNZC3uVff9TqiTdSrl0pMSCxE7Qda9QbSCvbvYh83QAucpdr'
}
npm install
